### ISSUE TITLE
Problem with NormaliseEnv

### ISSUE THREAD

**Issue by leandergrech** [MathPhysSim/FERMI_RL_Paper#1]
NormalizeEnv.scale_state_env() in [FERMI_RL_PAPER/naf2_new.py] produces only NaNs and Infs

Example:
`env = gym.make('MountainCarContinuous-v0')`
`nenv = NormalizeEnv(env)`
`print(nenv.scale_state_env(env.observation_space.low))`

Output:
`[-inf -inf]`
`FERMI_RL_PAPER/naf2_new.py:123: RuntimeWarning: divide by zero encountered in true_divide
  return (2 * ob - (self.obs_high + self.obs_low)) / scale`

**Comment by leandergrech** [comment]
Found the culprit.
[FERMI_RL_PAPER/naf2_new.py] line 90

`self.obs_low = self.env.observation_space.high`
should be:
`self.obs_low = self.env.observation_space.low`

**Comment by MathPhysSim** [comment]
Thanks, I changed the part.

**Comment by MathPhysSim** [comment]
Done!
