### ISSUE TITLE
TypeError when used in Colab

### ISSUE THREAD

**Issue by leandergrech** [MathPhysSim/FERMI_RL_Paper#2]
https://github.com/MathPhysSim/FERMI_RL_Paper/blob/0e5c13092bde74f8939a3dc26b7c3ed41c03a927/naf2_new.py#L188-L189

The above line causes:
`TypeError: Input 'y' of 'Mul' Op has type float64 that does not match type int32 of argument 'x'.`

**Comment by leandergrech** [comment]
Easy solution:
`neg_one = tf.constant(-1, dtype=np.float64)`
`V = tf.scalar_mul(neg_one, self.fc(h, 1, activation=tf.nn.leaky_relu,
                              kernel_initializer=self.kernel_initializer, name='V'))`

**Comment by MathPhysSim** [comment]
What about: V = -self.fc(h, 1, activation=tf.nn.leaky_relu, kernel_initializer=self.kernel_initializer, name='V')?
Thanks

**Comment by leandergrech** [comment]
> What about: V = -self.fc(h, 1, activation=tf.nn.leaky_relu, kernel_initializer=self.kernel_initializer, name='V')?
> Thanks

Works ;)
